language: generic

dist: bionic

branches:
  only:
    - master
    - develop
    - travis

sudo: required

services:
  - docker

before_install:
  - docker pull vimperator97/qt5

script:
  - scripts/travisDocker.sh

notifications:
  email:
    on_success: never
